// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: versions.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_versions_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_versions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_versions_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_versions_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_versions_2eproto;
namespace opencv_tensorflow {
class VersionDef;
struct VersionDefDefaultTypeInternal;
extern VersionDefDefaultTypeInternal _VersionDef_default_instance_;
}  // namespace opencv_tensorflow
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace opencv_tensorflow {

// ===================================================================


// -------------------------------------------------------------------

class VersionDef final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:opencv_tensorflow.VersionDef) */ {
 public:
  inline VersionDef() : VersionDef(nullptr) {}
  ~VersionDef() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VersionDef(
      ::google::protobuf::internal::ConstantInitialized);

  inline VersionDef(const VersionDef& from) : VersionDef(nullptr, from) {}
  inline VersionDef(VersionDef&& from) noexcept
      : VersionDef(nullptr, std::move(from)) {}
  inline VersionDef& operator=(const VersionDef& from) {
    CopyFrom(from);
    return *this;
  }
  inline VersionDef& operator=(VersionDef&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VersionDef& default_instance() {
    return *internal_default_instance();
  }
  static inline const VersionDef* internal_default_instance() {
    return reinterpret_cast<const VersionDef*>(
        &_VersionDef_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VersionDef& a, VersionDef& b) { a.Swap(&b); }
  inline void Swap(VersionDef* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VersionDef* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VersionDef* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VersionDef>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VersionDef& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VersionDef& from) { VersionDef::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VersionDef* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "opencv_tensorflow.VersionDef"; }

 protected:
  explicit VersionDef(::google::protobuf::Arena* arena);
  VersionDef(::google::protobuf::Arena* arena, const VersionDef& from);
  VersionDef(::google::protobuf::Arena* arena, VersionDef&& from) noexcept
      : VersionDef(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBadConsumersFieldNumber = 3,
    kProducerFieldNumber = 1,
    kMinConsumerFieldNumber = 2,
  };
  // repeated int32 bad_consumers = 3;
  int bad_consumers_size() const;
  private:
  int _internal_bad_consumers_size() const;

  public:
  void clear_bad_consumers() ;
  ::int32_t bad_consumers(int index) const;
  void set_bad_consumers(int index, ::int32_t value);
  void add_bad_consumers(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& bad_consumers() const;
  ::google::protobuf::RepeatedField<::int32_t>* mutable_bad_consumers();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_bad_consumers() const;
  ::google::protobuf::RepeatedField<::int32_t>* _internal_mutable_bad_consumers();

  public:
  // int32 producer = 1;
  void clear_producer() ;
  ::int32_t producer() const;
  void set_producer(::int32_t value);

  private:
  ::int32_t _internal_producer() const;
  void _internal_set_producer(::int32_t value);

  public:
  // int32 min_consumer = 2;
  void clear_min_consumer() ;
  ::int32_t min_consumer() const;
  void set_min_consumer(::int32_t value);

  private:
  ::int32_t _internal_min_consumer() const;
  void _internal_set_min_consumer(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:opencv_tensorflow.VersionDef)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedField<::int32_t> bad_consumers_;
    mutable ::google::protobuf::internal::CachedSize _bad_consumers_cached_byte_size_;
    ::int32_t producer_;
    ::int32_t min_consumer_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_versions_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VersionDef

// int32 producer = 1;
inline void VersionDef::clear_producer() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.producer_ = 0;
}
inline ::int32_t VersionDef::producer() const {
  // @@protoc_insertion_point(field_get:opencv_tensorflow.VersionDef.producer)
  return _internal_producer();
}
inline void VersionDef::set_producer(::int32_t value) {
  _internal_set_producer(value);
  // @@protoc_insertion_point(field_set:opencv_tensorflow.VersionDef.producer)
}
inline ::int32_t VersionDef::_internal_producer() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.producer_;
}
inline void VersionDef::_internal_set_producer(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.producer_ = value;
}

// int32 min_consumer = 2;
inline void VersionDef::clear_min_consumer() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.min_consumer_ = 0;
}
inline ::int32_t VersionDef::min_consumer() const {
  // @@protoc_insertion_point(field_get:opencv_tensorflow.VersionDef.min_consumer)
  return _internal_min_consumer();
}
inline void VersionDef::set_min_consumer(::int32_t value) {
  _internal_set_min_consumer(value);
  // @@protoc_insertion_point(field_set:opencv_tensorflow.VersionDef.min_consumer)
}
inline ::int32_t VersionDef::_internal_min_consumer() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.min_consumer_;
}
inline void VersionDef::_internal_set_min_consumer(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.min_consumer_ = value;
}

// repeated int32 bad_consumers = 3;
inline int VersionDef::_internal_bad_consumers_size() const {
  return _internal_bad_consumers().size();
}
inline int VersionDef::bad_consumers_size() const {
  return _internal_bad_consumers_size();
}
inline void VersionDef::clear_bad_consumers() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.bad_consumers_.Clear();
}
inline ::int32_t VersionDef::bad_consumers(int index) const {
  // @@protoc_insertion_point(field_get:opencv_tensorflow.VersionDef.bad_consumers)
  return _internal_bad_consumers().Get(index);
}
inline void VersionDef::set_bad_consumers(int index, ::int32_t value) {
  _internal_mutable_bad_consumers()->Set(index, value);
  // @@protoc_insertion_point(field_set:opencv_tensorflow.VersionDef.bad_consumers)
}
inline void VersionDef::add_bad_consumers(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_bad_consumers()->Add(value);
  // @@protoc_insertion_point(field_add:opencv_tensorflow.VersionDef.bad_consumers)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& VersionDef::bad_consumers() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:opencv_tensorflow.VersionDef.bad_consumers)
  return _internal_bad_consumers();
}
inline ::google::protobuf::RepeatedField<::int32_t>* VersionDef::mutable_bad_consumers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:opencv_tensorflow.VersionDef.bad_consumers)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_bad_consumers();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
VersionDef::_internal_bad_consumers() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.bad_consumers_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* VersionDef::_internal_mutable_bad_consumers() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.bad_consumers_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace opencv_tensorflow


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_versions_2eproto_2epb_2eh
